# Generated by Django 4.2.7 on 2025-09-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_currency_alter_wallet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT (Tether) - Primary'), ('BUSD', 'BUSD (Binance USD)'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BNB', 'Binance Coin'), ('USDC', 'USD Coin'), ('DAI', 'Dai Stablecoin'), ('KSH', 'Kenyan Shilling (Legacy)'), ('UGX', 'Ugandan Shilling (Legacy)'), ('TZS', 'Tanzanian Shilling (Legacy)')], default='USDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('USDT', 'USDT (Tether) - Primary'), ('BUSD', 'BUSD (Binance USD)'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BNB', 'Binance Coin'), ('USDC', 'USD Coin'), ('DAI', 'Dai Stablecoin'), ('KSH', 'Kenyan Shilling (Legacy)'), ('UGX', 'Ugandan Shilling (Legacy)'), ('TZS', 'Tanzanian Shilling (Legacy)')], default='USDT', max_length=10),
        ),
    ]
