# Generated by Django 4.2.7 on 2025-09-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_currency_alter_wallet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='country',
            field=models.CharField(choices=[('ZM', 'Zambia'), ('CD', 'Democratic Republic of Congo (DRC)'), ('TZ', 'Tanzania'), ('KE', 'Kenya'), ('UG', 'Uganda')], max_length=2),
        ),
        migrations.AlterField(
            model_name='p2pmerchant',
            name='country',
            field=models.CharField(choices=[('ZM', 'Zambia'), ('CD', 'Democratic Republic of Congo (DRC)'), ('TZ', 'Tanzania'), ('KE', 'Kenya'), ('UG', 'Uganda')], max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='countries',
            field=models.JSONField(default=list, help_text="List of country codes (e.g., ['ZM', 'KE', 'UG'])"),
        ),
    ]
