# Generated by Django 4.2.7 on 2025-09-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_agent_country_alter_p2pmerchant_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pmerchant',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, help_text='Select the payment methods this merchant supports', related_name='merchants', to='payments.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='p2pmerchant',
            name='supported_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
