# Generated by Django 4.2.7 on 2025-09-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_p2pmerchant_payment_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2pmerchant',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Account holder name as per bank records', max_length=100),
        ),
        migrations.AddField(
            model_name='p2pmerchant',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=30),
        ),
        migrations.AddField(
            model_name='p2pmerchant',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Bank branch name or code', max_length=100),
        ),
        migrations.AddField(
            model_name='p2pmerchant',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name of the bank', max_length=100),
        ),
        migrations.AddField(
            model_name='p2pmerchant',
            name='bank_swift_code',
            field=models.CharField(blank=True, help_text='Bank SWIFT/BIC code for international transfers', max_length=20),
        ),
        migrations.AddField(
            model_name='p2pmerchant',
            name='mobile_money_name',
            field=models.CharField(blank=True, help_text='Account holder name for mobile money', max_length=100),
        ),
        migrations.AddField(
            model_name='p2pmerchant',
            name='mobile_money_number',
            field=models.CharField(blank=True, help_text='Mobile money account number/phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='p2pmerchant',
            name='mobile_money_provider',
            field=models.CharField(blank=True, help_text='Mobile money provider (e.g., M-Pesa, Airtel Money, MTN Mobile Money)', max_length=50),
        ),
    ]
