# Generated by Django 4.2.7 on 2025-09-10 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('welcome_bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_profits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('maturity_date', models.DateTimeField()),
                ('is_principal_withdrawable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('basic', 'Basic Package'), ('standard', 'Standard Package'), ('premium', 'Premium Package')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('min_stake', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('welcome_bonus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_days', models.IntegerField(default=365)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.investment')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('is_withdrawn', models.BooleanField(default=False)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_distributions', to='trading.investment')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_record', to='trading.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profit histories',
                'ordering': ['-date_earned'],
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradingpackage'),
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
    ]
