# Generated by Django 4.2.7 on 2025-10-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpackage',
            name='duration_days',
            field=models.IntegerField(default=7),
        ),
    ]
