# Generated by Django 4.2.7 on 2025-10-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_update_existing_packages_to_7_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
