# Generated by Django 4.2.7 on 2025-10-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userreferralcode_alter_referral_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Referral code entered during signup, processed after email confirmation', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code_processed',
            field=models.BooleanField(default=False, help_text='Whether the pending referral code has been processed'),
        ),
    ]
