services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: tradevision
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  web:
    build: .
    command: >
      sh -c "
      python wait-for-it.py db 5432 &&
      echo 'Running migrations...' &&
      python manage.py migrate &&
      echo 'Collecting static files...' &&
      python manage.py collectstatic --noinput &&
      echo 'Starting Django server...' &&
      python manage.py runserver 0.0.0.0:7373
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "7373:7373"
    environment:
      - DEBUG=1
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    build: .
    command: >
      sh -c "
      python wait-for-it.py db 5432 &&
      python wait-for-it.py redis 6379 &&
      echo 'Starting Celery worker...' &&
      celery -A tradevision worker --loglevel=info
      "
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: >
      sh -c "
      python wait-for-it.py db 5432 &&
      python wait-for-it.py redis 6379 &&
      echo 'Starting Celery beat...' &&
      celery -A tradevision beat --loglevel=info
      "
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  media_volume: